///////////////////////////////////////////////////////////////
// This is generated code. 
//////////////////////////////////////////////////////////////
// Code is generated using LLBLGen Pro version: 2.6
// Code is generated on: Friday, August 07, 2009 1:24:45 PM
// Code is generated using templates: SD.TemplateBindings.SharedTemplates.NET20
// Templates vendor: Solutions Design.
// Templates version: 
//////////////////////////////////////////////////////////////
using System;
using System.Data;
using Kalibrasi.Data;
using Kalibrasi.Data.HelperClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace Kalibrasi.Data.FactoryClasses
{
	/// <summary>
	/// Generates IEntityFields instances for different kind of Entities. 
	/// This class is generated. Do not modify.
	/// </summary>
	public partial class EntityFieldsFactory
	{
		/// <summary>
		/// Private CTor, no instantiation possible.
		/// </summary>
		private EntityFieldsFactory()
		{
		}


		/// <summary>General factory entrance method which will return an EntityFields object with the format generated by the factory specified</summary>
		/// <param name="relatedEntityType">The type of entity the fields are for</param>
		/// <returns>The IEntityFields instance requested</returns>
		public static IEntityFields CreateEntityFieldsObject(Kalibrasi.Data.EntityType relatedEntityType)
		{
			IEntityFields fieldsToReturn=null;
			IInheritanceInfoProvider inheritanceProvider = InheritanceInfoProviderSingleton.GetInstance();
			IFieldInfoProvider fieldProvider = FieldInfoProviderSingleton.GetInstance();
			IPersistenceInfoProvider persistenceProvider = PersistenceInfoProviderSingleton.GetInstance();
			switch(relatedEntityType)
			{
				case Kalibrasi.Data.EntityType.MAlatEntity:
					fieldsToReturn = fieldProvider.GetEntityFields(inheritanceProvider, persistenceProvider, "MAlatEntity");
					break;
				case Kalibrasi.Data.EntityType.MDepartementEntity:
					fieldsToReturn = fieldProvider.GetEntityFields(inheritanceProvider, persistenceProvider, "MDepartementEntity");
					break;
				case Kalibrasi.Data.EntityType.MHakAksesEntity:
					fieldsToReturn = fieldProvider.GetEntityFields(inheritanceProvider, persistenceProvider, "MHakAksesEntity");
					break;
				case Kalibrasi.Data.EntityType.MLokasiEntity:
					fieldsToReturn = fieldProvider.GetEntityFields(inheritanceProvider, persistenceProvider, "MLokasiEntity");
					break;
				case Kalibrasi.Data.EntityType.MPicEntity:
					fieldsToReturn = fieldProvider.GetEntityFields(inheritanceProvider, persistenceProvider, "MPicEntity");
					break;
				case Kalibrasi.Data.EntityType.MUserEntity:
					fieldsToReturn = fieldProvider.GetEntityFields(inheritanceProvider, persistenceProvider, "MUserEntity");
					break;
				case Kalibrasi.Data.EntityType.THistoryAlatEntity:
					fieldsToReturn = fieldProvider.GetEntityFields(inheritanceProvider, persistenceProvider, "THistoryAlatEntity");
					break;
				case Kalibrasi.Data.EntityType.THistoryJadwalEntity:
					fieldsToReturn = fieldProvider.GetEntityFields(inheritanceProvider, persistenceProvider, "THistoryJadwalEntity");
					break;
				case Kalibrasi.Data.EntityType.TJadwalEntity:
					fieldsToReturn = fieldProvider.GetEntityFields(inheritanceProvider, persistenceProvider, "TJadwalEntity");
					break;
			}
			return fieldsToReturn;
		}
		
		/// <summary>General method which will return an array of IEntityFieldCore objects, used by the InheritanceInfoProvider. Only the fields defined in the entity are returned, no inherited fields.</summary>
		/// <param name="entityName">the name of the entity to get the fields for. Example: "CustomerEntity"</param>
		/// <returns>array of IEntityFieldCore fields, defined in the entity with the name specified</returns>
		internal static IEntityFieldCore[] CreateFields(string entityName)
		{
			IFieldInfoProvider fieldProvider = FieldInfoProviderSingleton.GetInstance();
			IPersistenceInfoProvider persistenceProvider = PersistenceInfoProviderSingleton.GetInstance();
			return fieldProvider.GetEntityFieldsArray(entityName, persistenceProvider);
		}

		/// <summary>General factory entrance method which will return a TypedView EntityFields object with the format generated by the factory specified</summary>
		/// <param name="relatedTypedViewType">The type of typed view the fields are for</param>
		/// <returns>The IEntityFields instance requested</returns>
		public static IEntityFields CreateTypedViewEntityFieldsObject(TypedViewType relatedTypedViewType)
		{
			IEntityFields fieldsToReturn=null;
			switch(relatedTypedViewType)
			{
				case TypedViewType.QDaftarIndukTypedView:
					fieldsToReturn = CreateQDaftarIndukTypedViewEntityFields();
					break;
				case TypedViewType.QMjadwalTypedView:
					fieldsToReturn = CreateQMjadwalTypedViewEntityFields();
					break;
				case TypedViewType.QTjadwalKalibrasiTypedView:
					fieldsToReturn = CreateQTjadwalKalibrasiTypedViewEntityFields();
					break;
				case TypedViewType.QTreminderTypedView:
					fieldsToReturn = CreateQTreminderTypedViewEntityFields();
					break;
			}
			return fieldsToReturn;
		}

		/// <summary>Creates a complete EntityFields instance for the QDaftarIndukEntity.</summary>
		/// <returns></returns>
		private static IEntityFields CreateQDaftarIndukTypedViewEntityFields()
		{
			IEntityFields fieldsToReturn = new EntityFields((int)QDaftarIndukFieldIndex.AmountOfFields, null, FieldInfoProviderSingleton.GetInstance().GetFieldIndexes("QDaftarIndukTypedView"));
			for(int i=0;i<(int)QDaftarIndukFieldIndex.AmountOfFields;i++)
			{
				fieldsToReturn[i] = EntityFieldFactory.Create((QDaftarIndukFieldIndex)i);
			}
			return fieldsToReturn;
		}

		/// <summary>Creates a complete EntityFields instance for the QMjadwalEntity.</summary>
		/// <returns></returns>
		private static IEntityFields CreateQMjadwalTypedViewEntityFields()
		{
			IEntityFields fieldsToReturn = new EntityFields((int)QMjadwalFieldIndex.AmountOfFields, null, FieldInfoProviderSingleton.GetInstance().GetFieldIndexes("QMjadwalTypedView"));
			for(int i=0;i<(int)QMjadwalFieldIndex.AmountOfFields;i++)
			{
				fieldsToReturn[i] = EntityFieldFactory.Create((QMjadwalFieldIndex)i);
			}
			return fieldsToReturn;
		}

		/// <summary>Creates a complete EntityFields instance for the QTjadwalKalibrasiEntity.</summary>
		/// <returns></returns>
		private static IEntityFields CreateQTjadwalKalibrasiTypedViewEntityFields()
		{
			IEntityFields fieldsToReturn = new EntityFields((int)QTjadwalKalibrasiFieldIndex.AmountOfFields, null, FieldInfoProviderSingleton.GetInstance().GetFieldIndexes("QTjadwalKalibrasiTypedView"));
			for(int i=0;i<(int)QTjadwalKalibrasiFieldIndex.AmountOfFields;i++)
			{
				fieldsToReturn[i] = EntityFieldFactory.Create((QTjadwalKalibrasiFieldIndex)i);
			}
			return fieldsToReturn;
		}

		/// <summary>Creates a complete EntityFields instance for the QTreminderEntity.</summary>
		/// <returns></returns>
		private static IEntityFields CreateQTreminderTypedViewEntityFields()
		{
			IEntityFields fieldsToReturn = new EntityFields((int)QTreminderFieldIndex.AmountOfFields, null, FieldInfoProviderSingleton.GetInstance().GetFieldIndexes("QTreminderTypedView"));
			for(int i=0;i<(int)QTreminderFieldIndex.AmountOfFields;i++)
			{
				fieldsToReturn[i] = EntityFieldFactory.Create((QTreminderFieldIndex)i);
			}
			return fieldsToReturn;
		}

		#region Included Code

		#endregion
	}
}
